### Cadastro de Usuário
POST http://localhost:5284/api/usuarios/cadastrar
Content-Type: application/json

{
    "nome": "Alice",
    "dataDeNascimento": "2000-01-01"
}

### Listagem de Usuários
GET http://localhost:5284/api/usuarios/listar

### Buscar Usuário por ID
GET http://localhost:5284/api/usuarios/buscar/c02ad106-80fd-47e7-989c-ce6bf1ac0ce0

### Deletar Usuário por ID
DELETE http://localhost:5284/api/usuarios/deletar/bb74e549-9cfc-44ac-bf2a-780fd8687e20

### Alterar Usuário por ID
PUT http://localhost:5284/api/usuarios/alterar/c02ad106-80fd-47e7-989c-ce6bf1ac0ce0
Content-Type: application/json

{
    "nome": "Felipe",
    "dataDeNascimento": "1998-05-23"
}
